openapi: 3.0.3
info:
  title: Swagger machinestore - OpenAPI 3.0
  description: |-
    This is a sample machine Store Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the machine store, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

    _If you're looking for the Swagger 2.0/OAS 2.0 version of machinestore, then click [here](https://editor.swagger.io/?url=https://machinestore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load machinestore OAS 2.0` menu option!_
    
    Some useful links:
    - [The machine Store repository](https://github.com/swagger-api/swagger-machinestore)
    - [The source API definition for the machine Store](https://github.com/swagger-api/swagger-machinestore/blob/master/src/main/resources/openapi.yaml)
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://localhost/api/v1
tags:
  - name: build
  - name: machine
    description: Everything about your machines
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /machines/{machineId}:
    get:
      tags:
        - machine
      summary: Find machine by ID
      description: Returns a single machine
      operationId: getMachineById
      parameters:
        - name: machineId
          in: path
          description: ID of machine to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Machine'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Machine'
        '400':
          description: Invalid ID supplied
        '404':
          description: machine not found
      security:
        - api_key: []
        - machinestore_auth:
            - write:machines
            - read:machines
components:
  schemas:
    Machine:
      required:
        - name
        - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: doggie
        photoUrls:
          type: array
          xml:
            wrapped: true
          items:
            type: string
            xml:
              name: photoUrl
        status:
          type: string
          description: machine status in the store
          enum:
            - available
            - pending
            - sold
      xml:
        name: machine
  requestBodies:
    machine:
      description: machine object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Machine'
        application/xml:
          schema:
            $ref: '#/components/schemas/Machine'
  securitySchemes:
    machinestore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://machinestore3.swagger.io/oauth/authorize
          scopes:
            write:machines: modify machines in your account
            read:machines: read your machines
    api_key:
      type: apiKey
      name: api_key
      in: header
